=== nibbio84/sea-surf/trunk/sea-surf/src/main/resources/META-INF/sea-surf-config_1_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.nerdammer.it/sea-surf-config_1_0" xmlns:tns="http://www.nerdammer.it/sea-surf-config_1_0" elementFormDefault="qualified">

    <element name="sea-surf-config" type="tns:sea-surf-config"></element>

    <complexType name="request-type">
    	<all>
    		<element name="pattern">
    			<simpleType>
    				<restriction base="string">
    					<minLength value="1"></minLength>
    					<pattern value="(/).*"></pattern>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="methods" type="tns:methods" maxOccurs="1" minOccurs="0"></element>
    	</all>
    </complexType>

    <complexType name="methods">
    	<sequence>
    		<element name="method" maxOccurs="unbounded"
    			minOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="GET"></enumeration>
    					<enumeration value="POST"></enumeration>
    					<enumeration value="PUT"></enumeration>
    					<enumeration value="HEAD"></enumeration>
    					<enumeration value="DELETE"></enumeration>
    					<enumeration value="OPTIONS"></enumeration>
    					<enumeration value="TRACE"></enumeration>
    					<enumeration value="CONNECT"></enumeration>
    					<enumeration value="PATCH"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    	</sequence>
    </complexType>


    <complexType name="request-type-collection">
    	<sequence>
    		<element name="request-type" type="tns:request-type" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>


    <complexType name="security-token-constraint">
    	<all>
    		<element name="include" type="tns:request-type-collection"
    			maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="exclude" type="tns:request-type-collection"
    			maxOccurs="1" minOccurs="0">
    		</element>
    	</all>
    </complexType>

    <complexType name="sea-surf-config">
    	<all>
    		<element name="security-token-constraints"
    			type="tns:security-token-constraints" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="referer-constraints"
    			type="tns:referer-constraints" maxOccurs="1" minOccurs="0">
    		</element>
    		<element name="preferences" type="tns:preferences" maxOccurs="1" minOccurs="0"></element>
    	</all>
    </complexType>

    <complexType name="referer-constraint">
    	<all>
    		<element name="on-missing-referer" maxOccurs="1"
    			minOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="BLOCK"></enumeration>
    					<enumeration value="ALLOW"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
            <element name="include-origin" type="tns:request-origin"
    			maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="exclude-origin" type="tns:request-origin"
    			maxOccurs="1" minOccurs="0">
    		</element>
    		<element name="include" type="tns:request-type-collection"
    			maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="exclude" type="tns:request-type-collection"
    			maxOccurs="1" minOccurs="0">
    		</element>
    	</all>
    </complexType>
    

    <complexType name="request-origin">
    	<sequence>
    		<choice maxOccurs="unbounded" minOccurs="1">
    			<element name="page" type="tns:origin-page"
    				maxOccurs="1" minOccurs="1">
    			</element>
    			<element name="domain" type="tns:origin-domain"
    				maxOccurs="1" minOccurs="1">
    			</element>
    		</choice>
    	</sequence>
    </complexType>
    


    <simpleType name="origin-page">
    	<restriction base="string">
    		<minLength value="1"></minLength>
    	</restriction>
    </simpleType>

    <simpleType name="origin-domain">
    	<restriction base="string">
    		<minLength value="1"></minLength>
    	</restriction>
    </simpleType>


    <complexType name="referer-constraints">
    	<sequence>
    		<element name="referer-constraint" type="tns:referer-constraint" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="security-token-constraints">
    	<sequence>
    		<element name="security-token-constraint" type="tns:security-token-constraint" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="preferences">
    	<all>
    		<element name="token-length" minOccurs="0" maxOccurs="1"
    			nillable="false">
    			<simpleType>
    				<restriction base="int">
    					<minInclusive value="12"></minInclusive>
    					<maxInclusive value="50"></maxInclusive>
    					<enumeration value="12"></enumeration>
    					<enumeration value="14"></enumeration>
    					<enumeration value="16"></enumeration>
    					<enumeration value="18"></enumeration>
    					<enumeration value="20"></enumeration>
    					<enumeration value="22"></enumeration>
    					<enumeration value="24"></enumeration>
    					<enumeration value="26"></enumeration>
    					<enumeration value="28"></enumeration>
    					<enumeration value="30"></enumeration>
    					<enumeration value="32"></enumeration>
    					<enumeration value="34"></enumeration>
    					<enumeration value="36"></enumeration>
    					<enumeration value="38"></enumeration>
    					<enumeration value="40"></enumeration>
    					<enumeration value="42"></enumeration>
    					<enumeration value="44"></enumeration>
    					<enumeration value="46"></enumeration>
    					<enumeration value="48"></enumeration>
    					<enumeration value="50"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="token-parameter-name" maxOccurs="1"
    			minOccurs="0">
    			<simpleType>
    				<restriction base="string">
    					<minLength value="1"></minLength>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="token-storage" maxOccurs="1" minOccurs="0">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="SESSION"></enumeration>
    					<enumeration value="COOKIE"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="token-name-on-storage" maxOccurs="1"
    			minOccurs="0">
    			<simpleType>
    				<restriction base="string">
    					<minLength value="1"></minLength>
    				</restriction>
    			</simpleType>
    		</element>
    	</all>
    </complexType>
</schema>

=== nibbio84/sea-surf/trunk/sea-surf-test/src/main/resources/sea-surf-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<sea-surf-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.nerdammer.it/sea-surf-config_1_0"
	xsi:schemaLocation="http://www.nerdammer.it/sea-surf-config_1_0 http://sea-surf.googlecode.com/files/sea-surf-config_1_0.xsd">
	
    <referer-constraints>
		<referer-constraint>
		    
		    <on-missing-referer>BLOCK</on-missing-referer>
		    
		    <include>
		        <request-type>
		            <pattern>/*</pattern>
		            <methods>
		                <method>POST</method>
		                <method>PUT</method>
		            </methods>
		        </request-type>
		    </include>
		    
		    <exclude>
		        <request-type>
					<pattern>/myPage</pattern>
		    	</request-type>
		    </exclude>
		    
		    <include-origin>
		        <domain>www.mydomain.*</domain>
		        <page>http://www2.aaa.it/page</page>
		    </include-origin>
		    
		</referer-constraint>        
    </referer-constraints>
    
    <security-token-constraints>
        <security-token-constraint>
            <include>
                <request-type>
                    <pattern>/page2.jsp</pattern>
                </request-type>
            </include>
        </security-token-constraint>
    </security-token-constraints>
        
    <preferences>
        <token-storage>SESSION</token-storage>
        
    </preferences>
</sea-surf-config>

=== nibbio84/sea-surf/tags/sea-surf-1.0.0/src/test/resources/std-test-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<sea-surf-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.nerdammer.it/sea-surf-config_1_0"
	xsi:schemaLocation="http://www.nerdammer.it/sea-surf-config_1_0 /Users/nicolaferraro/Workspaces/CSRF/sea-surf/src/main/resources/META-INF/sea-surf-config_1_0.xsd">

	<security-token-constraints>
		<security-token-constraint>
			<include>
				<request-type>
					<pattern>/*</pattern>
					<methods>
						<method>POST</method>
					</methods>
				</request-type>
			</include>
			
			<exclude>
				<request-type>
					<pattern>/ciccia</pattern>
				</request-type>
			</exclude>
			
		</security-token-constraint>
	</security-token-constraints>
	
	<preferences>
		<token-storage>COOKIE</token-storage>
	</preferences>

</sea-surf-config>

=== nibbio84/sea-surf/trunk/sea-surf/src/test/resources/std-test-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<sea-surf-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.nerdammer.it/sea-surf-config_1_0"
	xsi:schemaLocation="http://www.nerdammer.it/sea-surf-config_1_0 /Users/nicolaferraro/Workspaces/CSRF/sea-surf/src/main/resources/META-INF/sea-surf-config_1_0.xsd">

	<referer-constraints>
		<referer-constraint>
			<include-origin>
				<page>http://www.google.*</page>
				<page>https://www.google.*</page>
			</include-origin>

			<include>
				<request-type>
					<pattern>/action</pattern>
				</request-type>
			</include>
		</referer-constraint>
		
		<referer-constraint>
			<include-origin>
				<domain>www.nerdammer.it</domain>
			</include-origin>

			<include>
				<request-type>
					<pattern>/azion*</pattern>
					<methods>
						<method>POST</method>
					</methods>
				</request-type>
			</include>
		</referer-constraint>
	</referer-constraints>


</sea-surf-config>

=== nibbio84/sea-surf/trunk/sea-surf-test/src/main/resources/META-INF/sea-surf-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<sea-surf-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.nerdammer.it/sea-surf-config_1_0"
	xsi:schemaLocation="http://www.nerdammer.it/sea-surf-config_1_0 http://sea-surf.googlecode.com/files/sea-surf-config_1_0.xsd">
	
    
    <security-token-constraints>
        <security-token-constraint>
            <include>
                <request-type>
                    <pattern>/page2.jsp</pattern>
                </request-type>
            </include>
        </security-token-constraint>
        
    </security-token-constraints>
        
    <preferences>
        <token-storage>COOKIE</token-storage>
        
    </preferences>
</sea-surf-config>

=== nibbio84/sea-surf/trunk/sea-surf/src/test/resources/sample-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<sea-surf-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.nerdammer.it/sea-surf-config_1_0"
	xsi:schemaLocation="http://www.nerdammer.it/sea-surf-config_1_0 /Users/nicolaferraro/Workspaces/CSRF/sea-surf/src/main/resources/META-INF/sea-surf-config_1_0.xsd">
	
	<security-token-constraints>
		<security-token-constraint>
			<scope>SESSION</scope>
			<include>
				<request-type>
					<pattern>/*</pattern>
					<methods>
						<method>POST</method>
						<method>CONNECT</method>
					</methods>
				</request-type>
			</include>

			<exclude>
				<request-type>
					<pattern>/DataImport*</pattern>
				</request-type>
			</exclude>
		</security-token-constraint>
	</security-token-constraints>


	<referer-constraints>
		<referer-constraint>
			<include-origin>
				<page>ss</page>
				<domain></domain>
				<page>ssww</page>
			</include-origin>

			<include>
				<request-type>
					<pattern>/as</pattern>
				</request-type>
			</include>
		</referer-constraint>
	</referer-constraints>

</sea-surf-config>
